name: Schedule Test

on:
  schedule:
    - cron: '30 11,12,13,14 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SCHEDULE TRIGGERED"
          date
